export const Routes = {
  backendRoot: "https://api.nussu.org.sg",
  index: "/",
  home: "/home",
  aboutUs: "/aboutus/aboutus",
  governance: "/aboutus/governance",
  history: "/aboutus/history",
  ourTeam: "/aboutus/ourteam",
  presidentMessage: "/aboutus/president",
  contact: "/contact",
  events: "/events",
  freshmen: "/freshmen",
  ourWork: "/our-work",
  services: "/services",
  joinus: "/join-us",
  form: "https://api.sheety.co/834264eebe4376abdca9016e1caed4e1/nussuWebsiteForm/sheet1",
};
